"""Outbound webhook domain models: reseller-registered endpoints and delivery attempts."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datetime import datetime

    from src.shared.types import TenantId, WebhookEndpointId

# The only event types actually routed to webhook-dispatch.fifo (messaging-topology.md's
# locked SNS filter policy) — an endpoint's `event_types` is a subset of this, or None
# for "all of these".
DISPATCHABLE_EVENT_TYPES = frozenset(
    {
        "OrderSentToErp",
        "OrderConfirmed",
        "OrderFulfilled",
        "OrderClosed",
        "OrderRejected",
        "OrderRetrying",
    }
)


@dataclass
class WebhookEndpoint:
    """One reseller-owned HTTP endpoint. `secret_ref` resolves the HMAC signing secret —
    generated by the app at registration and shown to the reseller exactly once, never
    stored raw (mirrors `ErpConnection.webhook_secret_ref`)."""

    endpoint_id: WebhookEndpointId
    tenant_id: TenantId
    name: str
    url: str
    secret_ref: str
    event_types: frozenset[str] | None  # None = all DISPATCHABLE_EVENT_TYPES
    is_active: bool = True

    def subscribes_to(self, event_type: str) -> bool:
        return self.is_active and (self.event_types is None or event_type in self.event_types)


class DeliveryStatus(str, Enum):
    DELIVERED = "DELIVERED"
    RETRYING = "RETRYING"
    FAILED = "FAILED"  # exhausted retries (dead-lettered)


@dataclass
class WebhookDelivery:
    """One (endpoint, event) delivery attempt record, updated in place across retries —
    not one row per HTTP attempt. `attempts` mirrors messaging-topology.md's locked
    `maxReceiveCount=5`: once it hits that, the delivery is FAILED even though the
    underlying SQS message also lands in `webhook-dispatch-dlq.fifo` around the same
    time — two views of the same limit, not two separate policies to keep in sync."""

    delivery_id: str
    endpoint_id: WebhookEndpointId
    tenant_id: TenantId
    order_id: str
    event_type: str
    event_id: str
    occurred_at: datetime
    status: DeliveryStatus
    attempts: int
    last_response: str | None
    payload: dict
