"""Ports for the quoting module."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from src.shared.types import TenantId

    from ..domain.models import Quote, Subsidiary


class QuoteRepository(Protocol):
    def add(self, quote: Quote) -> None: ...
    def update(self, quote: Quote) -> None: ...
    def get(self, quote_id: str) -> Quote | None: ...
    def list_by_tenant(self, tenant_id: TenantId) -> list[Quote]: ...
    def list_all(self) -> list[Quote]: ...


class SubsidiaryRepository(Protocol):
    def add(self, company: Subsidiary) -> None: ...
    def get(self, subsidiary_id: str) -> Subsidiary | None: ...
    def list_all(self) -> list[Subsidiary]: ...


class SubsidiaryRouteRepository(Protocol):
    """Which ERP connection an subsidiary's quotes currently route to — at most
    one per company, enforced by being the only row for it (no separate active flag)."""

    def set_route(self, subsidiary_id: str, connection_id: str) -> None: ...
    def get_route(self, subsidiary_id: str) -> str | None: ...
