"""Ports for the quoting module."""

from __future__ import annotations

from typing import Protocol

from src.shared.types import TenantId

from ..domain.models import OperatingCompany, Quote


class QuoteRepository(Protocol):
    def add(self, quote: Quote) -> None: ...
    def update(self, quote: Quote) -> None: ...
    def get(self, quote_id: str) -> Quote | None: ...
    def list_by_tenant(self, tenant_id: TenantId) -> list[Quote]: ...
    def list_all(self) -> list[Quote]: ...


class OperatingCompanyRepository(Protocol):
    def add(self, company: OperatingCompany) -> None: ...
    def get(self, operating_company_id: str) -> OperatingCompany | None: ...
    def list_all(self) -> list[OperatingCompany]: ...
